export const TABLE_HEAD = ["Status", "Task Name", "Created by", "Priority", "Date"];
export const TABLE_ROWS = [
  {
    img: "https://docs.material-tailwind.com/img/logos/logo-spotify.svg",
    name: "Spotify",
    taskName: "Contract #2564 need Charlie Puth’s signature",
    date: "Brandon Mango",
    status: "paid",
    account: "visa",
    accountNumber: "1234",
    expiry: "06/2026",
  },
  {
    img: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
    name: "Amazon",
    taskName: "Contract #2564 need Charlie Puth’s signature",
    date: "Brandon Mango",
    status: "paid",
    account: "master-card",
    accountNumber: "1234",
    expiry: "06/2026",
  },
  {
    img: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
    name: "Amazon",
    taskName: "Contract #2564 need Charlie Puth’s signature",
    date: "Brandon Mango",
    status: "paid",
    account: "master-card",
    accountNumber: "1234",
    expiry: "06/2026",
  },
  {
    img: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
    name: "Amazon",
    taskName: "Contract #2564 need Charlie Puth’s signature",
    date: "Brandon Mango",
    status: "paid",
    account: "master-card",
    accountNumber: "1234",
    expiry: "06/2026",
  },
  {
    img: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
    name: "Amazon",
    taskName: "Contract #2564 need Charlie Puth’s signature",
    date: "Brandon Mango",
    status: "paid",
    account: "master-card",
    accountNumber: "1234",
    expiry: "06/2026",
  },
  {
    img: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
    name: "Amazon",
    taskName: "Contract #2564 need Charlie Puth’s signature",
    date: "Brandon Mango",
    status: "paid",
    account: "master-card",
    accountNumber: "1234",
    expiry: "06/2026",
  },
  {
    img: "https://docs.material-tailwind.com/img/logos/logo-amazon.svg",
    name: "Amazon",
    taskName: "Contract #2564 need Charlie Puth’s signature",
    date: "Brandon Mango",
    status: "paid",
    account: "master-card",
    accountNumber: "1234",
    expiry: "06/2026",
  },
  {
    img: "https://docs.material-tailwind.com/img/logos/logo-pinterest.svg",
    name: "Pinterest",
    taskName: "Contract #2564 need Charlie Puth’s signature",
    date: "Brandon Mango",
    status: "pending",
    account: "master-card",
    accountNumber: "1234",
    expiry: "06/2026",
  },

];
